### PR TITLE
add reload button

### PR DESCRIPTION
**Pull request by neo773**
This PR adds a reload button

https://github.com/Cap-go/capacitor-inappbrowser/assets/62795688/b4d8d19c-af1e-4f67-803b-7c449923df0d

/claim #73

### CODE REVIEW

**Comment by riderx** [comment]
Thanks @neo773, your PR is nice but the Android part is missing i think or that was already working ?

**Comment by neo773** [comment]
@riderx Added android!

**Comment by riderx** [comment]
Can you share android video too ?

**Comment by riderx** [comment]
Oh i just made merge conflict for the close modal feature, if you are still around

**Comment by riderx** [comment]
https://github.com/Cap-go/capacitor-inappbrowser/assets/4084527/4c427bc1-b327-4e72-890e-375c5a60f6dd

**Pull request merged**
