### PR TITLE
feat: Add reload button in openWebView

### PR DESCRIPTION
**Pull request by ayusham001**
/claim #73

### CODE REVIEW

**Comment by ayusham001** [comment]
Hey @riderx 
Thank you for your feedback! I apologize for the misunderstanding regarding the initial task, 
I'm glad you like the feature Please review the changes.

**Comment by ayusham001** [comment]
Hello @riderx, it seems like the issue has been closed. What about the feature I added that is callable from JS?

**Comment by riderx** [comment]
Can you fix your conflict, I will tips you then

**Comment by ayusham001** [comment]
Hi @riderx, I have resolved some conflicts. 
Please take a look at it and let me know if there are any further requirements.
Thank you.

**Comment by ayusham001** [comment]
Hi @riderx, Just checking in with you since it has been a while. Please revert back to this whenever you find it suitable, I will be looking forward to your reply.

**Comment by riderx** [comment]
i'm not sure to understand what revert you talk about ^^
i saw you added in pakcage json a peer dep of the package itself, I think that a mistake, can you update it ?

**Comment by ayusham001** [comment]
hii @riderx I have made some changes

**Comment by riderx** [comment]
@ayusham001 thanks it only miss the typescript definition now :)

**Comment by ayusham001** [comment]
@riderx Check it out :)

**Comment by riderx** [comment]
Can you run build command, fmt, and verify ?

**Comment by ayusham001** [comment]
@riderx I have done changes which I found to be done.

**Comment by ayusham001** [comment]
Hi @riderx, Hopefully, you have looked into my recent changes to the PR. Please provide me with the necessary feedback.

**Comment by riderx** [comment]
Thanks a lot !

**Comment by ayusham001** [comment]
Thank you @riderx for your support and consideration.

**Comment by riderx** [comment]
Hey @ayusham001 seems you got the tip plus the reward as well.
I know it could look nice for you.
But this was not supposed to happen.
I'm happy about your work, and I was comfortable to tip you, but right now it feels a bit unfair to the original one PR.
So I have ask Algora team to take a look on this

**Comment by ayusham001** [comment]
Hello @riderx,  yes I noticed the update right now. Of course, it was a little sad to see the reward get refunded since I worked hard for the PR, but I also understand your point. Besides, I trust your judgment of the same. 
I am grateful for the tip and my PR getting merged. 
Thank you.

**Pull request merged**
