### PR TITLE
add option to prevents deep links from opening directly in one app when multiple duplicate apps are installed on the device

### PR DESCRIPTION
**Pull request by JeetuChoudhary**
This pull request adds new functionality to the @capgo/in-app-browser plugin that prevents deep links from opening directly in one app when multiple duplicate apps are installed on the device. For instance, if both WhatsApp and WhatsApp Business are installed, the user will now be prompted to choose which app to open the link in.
This new feature helps to provide a better user experience by allowing users to easily choose which app to use for specific links, without being redirected to a default app.
I have tested this implementation and it works as expected. I believe this feature will be a valuable addition to the @capgo/in-app-browser plugin and I look forward to your feedback

### CODE REVIEW

**Comment by riderx** [comment]
Thanks a lot for the PR !
To be able to go forward can you check your merge conflict ?
Also i see you did this change on android only, can we do it in ios ?
You need to update the Typescript declaration as well with the new option, this will generate the documentation update.

**Comment by JeetuChoudhary** [comment]
Thank you for your response! 
I have resolved the merge conflicts and pushed the changes to a new branch.
Regarding your comment about implementing the change for iOS, I was facing this issue only in Android. It was working as expected in ios. That is why I made changes only in Android.

**Comment by riderx** [comment]
Can you run `npm run fmt` it seems your linter made lot of change, so please run the lint to have only the necessary change pushed

**Comment by JeetuChoudhary** [comment]
Absolutely, I've just finished running npm run fmt and have pushed the updated commit. Please let me know if there's anything else I can do to ensure the success of this pull request.

**Review by riderx — APPROVED** [review]

**Pull request merged**
